name: Windows Server 2019

on: 
  workflow_dispatch:

jobs:
  build:
    name: Windows 10 Build
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Creating Local User
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:WINDOWS_USER_PASSWORD -Force)
      env:
        WINDOWS_USER_PASSWORD: ${{ secrets.WINDOWS_USER_PASSWORD }}
    - name: Download
      run: |
       Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
       Invoke-WebRequest https://drive.google.com/file/d/18-RixASBpCMxorOEiloQ7uZDjFz4X0w_/view?usp=sharing -OutFile nssm.exe
       Invoke-WebRequest https://raw.githubusercontent.com/arurdpsha/AviVPS/main/resources/ngrok-user.bat -OutFile ngrok-user.bat
       Invoke-WebRequest https://raw.githubusercontent.com/arurdpsha/AviVPS/main/resources/ngrok-start.bat -OutFile ngrok-start.bat
       Invoke-WebRequest https://raw.githubusercontent.com/arurdpsha/AviVPS/main/resources/ngrok-loop.bat -OutFile ngrok-loop.bat
    - name: Extract NGROK 
      run: |
       Expand-Archive ngrok.zip
      
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Installing Ngrok Process as a Windows Core Services
      run: start ngrok-start.bat
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Enabing Networking Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Setting up RDP TCP UserAuthentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connecting Process
      run: cmd /c ngrok-user.bat
    - name: Looping Process
      run: cmd /c ngrok-loop.bat
